### ISSUE TITLE
BUG: RCG CLV accelerator sporadically fails with NotImplementedError: Cannot apply ufunc <ufunc 'hyp2f1'> to mixed DataFrame and Series inputs

### ISSUE THREAD

**Issue by dbbnicole** [databricks-industry-solutions/customer-lifetime-value#1]
This is a bug in an external dependency package that is no longer actively maintained. See https://github.com/pandas-dev/pandas/issues/46138#

**Comment by coreyabs-db** [comment]
I worked around this in getting the solution accelerator ready for a conference by simply taking the .values of the Series objects we pass to the fitters. If that works for a fix here feel free to assign it to me and I'll clean it up and apply it after the conference.

**Comment by dbbnicole** [comment]
Thanks @coreyabs-db ! We have updated this accelerator to use btyd instead. Will monitor the stability of this accelerator and see if this flakey issue reappears.
